border_width = 2
margin = [4, 4]
default_border_color = "#121948"
floating_border_color = "#AEA5BA"
focused_border_color = "#e9cbc1"


col1 = "#324DA0"
col2 = "#5867A2"
col3 = "#9C748C"
col4 = "#7785AA"
col5 = "#6790DB"
col6 = "#AEA5BA"
col7 = "#e9cbc1"
col8 = "#a38e87"
col9 = "#324DA0"
col10 = "#5867A2"
col11 = "#9C748C"
col12 = "#7785AA"
col13 = "#6790DB"
col14 = "#AEA5BA"
col15 = "#e9cbc1"



background = "#121948"
foreground = "#e9cbc1"
